services:
  - type: web
    name: allconverterhub-api
    runtime: docker
    region: singapore
    plan: free
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    healthCheckPath: /api/v1/auth/health
    autoDeployTrigger: commit

    envVars:
      - key: MONGODB_URI
        sync: false

      - key: FRONTEND_URL
        value: https://allconverterhub.vercel.app

      - key: JWT_SECRET
        sync: false

      - key: RESEND_API_KEY
        sync: false

      - key: MAIL_FROM
        sync: false