import Link from "next/link";

import ToolCard from "@/components/ui/ToolCard";
import { getRelatedTools, getToolFaqs, getToolHowToSteps } from "@/lib/toolContent";
import { featuredTools, type Tool } from "@/lib/tools";

export default function ToolSeoContent({ tool }: { tool: Tool }) {
  const steps = getToolHowToSteps(tool);
  const faqs = getToolFaqs(tool);
  const relatedTools = getRelatedTools(tool, featuredTools);

  return <section className="mt-14 space-y-12 border-t border-slate-200 pt-12 dark:border-slate-800"><nav aria-label="Breadcrumb" className="text-sm text-slate-500 dark:text-slate-400"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/" className="hover:text-blue-600 dark:hover:text-blue-400">Home</Link></li><li aria-hidden="true">/</li><li><Link href="/#tool-discovery" className="hover:text-blue-600 dark:hover:text-blue-400">{tool.category}</Link></li><li aria-hidden="true">/</li><li className="font-medium text-slate-700 dark:text-slate-200" aria-current="page">{tool.title}</li></ol></nav><div className="grid gap-10 lg:grid-cols-2"><article><p className="text-sm font-semibold uppercase tracking-widest text-blue-600 dark:text-blue-400">How to use</p><h2 className="mt-2 text-3xl font-bold">How to use {tool.title}</h2><ol className="mt-6 space-y-4">{steps.map((step, index) => <li key={step} className="flex gap-4"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-blue-600 text-sm font-bold text-white">{index + 1}</span><span className="pt-0.5 text-slate-600 dark:text-slate-300">{step}</span></li>)}</ol></article><article><p className="text-sm font-semibold uppercase tracking-widest text-blue-600 dark:text-blue-400">FAQ</p><h2 className="mt-2 text-3xl font-bold">Frequently asked questions</h2><div className="mt-6 divide-y divide-slate-200 rounded-2xl border border-slate-200 dark:divide-slate-800 dark:border-slate-800">{faqs.map((faq) => <details key={faq.question} className="group p-5"><summary className="cursor-pointer list-none pr-8 font-semibold marker:hidden">{faq.question}<span className="float-right text-blue-600 transition group-open:rotate-45 dark:text-blue-400">+</span></summary><p className="mt-3 text-sm leading-6 text-slate-600 dark:text-slate-300">{faq.answer}</p></details>)}</div></article></div>{relatedTools.length > 0 && <div><div className="flex items-end justify-between gap-4"><div><p className="text-sm font-semibold uppercase tracking-widest text-blue-600 dark:text-blue-400">Keep exploring</p><h2 className="mt-2 text-3xl font-bold">Related tools</h2></div><Link href="/#tool-discovery" className="text-sm font-semibold text-blue-600 hover:text-blue-500 dark:text-blue-400">View all tools</Link></div><div className="mt-6 grid gap-6 md:grid-cols-2 lg:grid-cols-3">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.id} id={relatedTool.id} icon={relatedTool.icon} title={relatedTool.title} description={relatedTool.description} badge={relatedTool.badge} />)}</div></div>}</section>;
}
