"use client";

import Link from "next/link";
import { CheckCircle2, ChevronLeft, MailCheck, Shield } from "lucide-react";
import { useState, type FormEvent } from "react";
import { useAuth } from "@/components/providers/AuthProvider";
import { changePassword, resendVerificationEmail, updateProfile } from "@/lib/authApi";

export default function ProfileSettings() {
  const { isLoading, logout, refreshProfile, session, user } = useAuth();
  const [currentPassword, setCurrentPassword] = useState("");
  const [newPassword, setNewPassword] = useState("");
  const [message, setMessage] = useState("");
  const [error, setError] = useState("");
  const [saving, setSaving] = useState(false);

  if (isLoading) return <main className="mx-auto max-w-3xl animate-pulse px-4 py-12 sm:px-6"><div className="h-96 rounded-3xl bg-slate-200 dark:bg-slate-800" /></main>;
  if (!session || !user) return <main className="mx-auto max-w-xl px-4 py-20 text-center sm:px-6"><h1 className="text-3xl font-bold">Sign in to edit your profile</h1><Link className="mt-6 inline-flex rounded-xl bg-blue-600 px-5 py-3 font-semibold text-white" href="/">Go home</Link></main>;
  const authenticatedSession = session;

  const show = (nextMessage: string) => { setError(""); setMessage(nextMessage); };
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); const firstName = String(form.get("firstName") ?? ""); const lastName = String(form.get("lastName") ?? ""); setSaving(true); setError(""); try { await updateProfile(authenticatedSession, firstName, lastName); await refreshProfile(); show("Your profile has been updated."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update your profile."); } finally { setSaving(false); } }
  async function savePassword(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (newPassword.length < 12) { setError("Use a new password of at least 12 characters."); return; } setSaving(true); setError(""); try { await changePassword(authenticatedSession, currentPassword, newPassword); setCurrentPassword(""); setNewPassword(""); show("Password changed. Please sign in again to continue."); logout(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to change your password."); } finally { setSaving(false); } }
  async function resend() { setSaving(true); setError(""); try { show((await resendVerificationEmail(authenticatedSession)).message); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to resend the verification email."); } finally { setSaving(false); } }

  return <main className="mx-auto max-w-3xl px-4 py-10 sm:px-6"><Link className="inline-flex items-center gap-2 text-sm font-semibold text-blue-600 hover:underline" href="/dashboard"><ChevronLeft className="h-4 w-4" />Dashboard</Link><h1 className="mt-4 text-3xl font-bold">Profile & security</h1><p className="mt-2 text-slate-600 dark:text-slate-400">Manage your account details and keep it secure.</p>{error && <p className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-700 dark:bg-red-950/40 dark:text-red-200">{error}</p>}{message && <p className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-700 dark:bg-emerald-950/40 dark:text-emerald-200">{message}</p>}<section className="mt-7 rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900"><div className="flex items-start gap-3"><MailCheck className="mt-0.5 h-5 w-5 text-blue-600" /><div><h2 className="font-bold">Email verification</h2><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{user.email}</p>{user.emailVerified ? <p className="mt-3 flex items-center gap-2 text-sm font-semibold text-emerald-600"><CheckCircle2 className="h-4 w-4" />Verified email</p> : <button className="mt-3 text-sm font-semibold text-blue-600 hover:underline" disabled={saving} onClick={() => void resend()} type="button">Resend verification email</button>}</div></div></section><form className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900" onSubmit={saveProfile}><h2 className="font-bold">Your name</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><NameInput defaultValue={user.firstName} label="First name" name="firstName" /><NameInput defaultValue={user.lastName} label="Last name" name="lastName" /></div><button className="mt-5 rounded-xl bg-blue-600 px-5 py-2.5 font-semibold text-white disabled:opacity-50" disabled={saving} type="submit">Save profile</button></form><form className="mt-6 rounded-2xl border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-slate-900" onSubmit={savePassword}><div className="flex items-center gap-3"><Shield className="h-5 w-5 text-blue-600" /><h2 className="font-bold">Change password</h2></div><div className="mt-4 grid gap-4"><Input label="Current password" onChange={setCurrentPassword} type="password" value={currentPassword} /><Input label="New password" onChange={setNewPassword} type="password" value={newPassword} /></div><p className="mt-2 text-xs text-slate-500">At least 12 characters. Changing your password signs out other sessions.</p><button className="mt-5 rounded-xl bg-slate-900 px-5 py-2.5 font-semibold text-white disabled:opacity-50 dark:bg-white dark:text-slate-900" disabled={saving} type="submit">Change password</button></form></main>;
}

function NameInput({ defaultValue, label, name }: { defaultValue: string; label: string; name: string }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<input className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-slate-950 outline-none ring-blue-500 focus:ring-2 dark:border-slate-600 dark:bg-slate-950 dark:text-white" defaultValue={defaultValue} maxLength={60} name={name} required /></label>; }
function Input({ label, onChange, type = "text", value }: { label: string; onChange: (value: string) => void; type?: string; value: string }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<input className="rounded-xl border border-slate-300 bg-white px-3 py-2.5 text-slate-950 outline-none ring-blue-500 focus:ring-2 dark:border-slate-600 dark:bg-slate-950 dark:text-white" maxLength={type === "text" ? 60 : undefined} minLength={type === "password" ? 12 : undefined} onChange={(event) => onChange(event.target.value)} required type={type} value={value} /></label>; }
